printWidth: 120
semi: false
trailingComma: none
arrowParens: avoid
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder:
  # (Run in WSL) $ node -p '"^(?:" + require("repl")._builtinLibs.join("|") + ")$"'
  - "^(?:assert|assert/strict|async_hooks|buffer|child_process|cluster|console|constants|crypto|dgram|diagnostics_channel|dns|dns/promises|domain|events|fs|fs/promises|http|http2|https|inspector|module|net|os|path|path/posix|path/win32|perf_hooks|process|punycode|querystring|readline|readline/promises|repl|stream|stream/consumers|stream/promises|stream/web|string_decoder|sys|timers|timers/promises|tls|trace_events|tty|url|util|util/types|v8|vm|worker_threads|zlib)$"
  - "<THIRD_PARTY_MODULES>"
  # File extension is required in Node.js ESM imports https://nodejs.org/docs/latest-v17.x/api/esm.html#mandatory-file-extensions
  - "^\\.{1,2}\\/.+\\.(js|ts|jsx|tsx)$"
importOrderSeparation: true
importOrderSortSpecifiers: true
